#include<stdio.h>
#include<math.h>

int main()
{
    float PRECIOM2,IVA,L,LADOA,BASETRIANGULO,LADOC,ALTURATRIANGULO,AREATRIANGULO,AREAPARALELOGRAMO,AREATOTAL,PRECIOTOTAL,PRECIOTOTALCONIVA;
        PRECIOM2=9266;
        IVA=0.16;
        L=12;
        BASETRIANGULO=1.0/2.0;
        LADOC=L;
        LADOA= sqrt((L*L)+(BASETRIANGULO*BASETRIANGULO));
        ALTURATRIANGULO= sqrt((L*L)-(1.0/4.0));
        AREATRIANGULO=(1.0/2.0)*(BASETRIANGULO*ALTURATRIANGULO);
        AREAPARALELOGRAMO= L*((1.0/2.0)*L);
        AREATOTAL=AREATRIANGULO+AREAPARALELOGRAMO;
        PRECIOTOTAL=AREATOTAL*PRECIOM2;
        PRECIOTOTALCONIVA=(PRECIOTOTAL*IVA)+PRECIOTOTAL;

        printf("EL PRECIO TOTAL DEL TERRENO DE DONJOSE ES DE:%f",PRECIOTOTALCONIVA);

    return 0;


}
